# Generated by Django 5.0.1 on 2024-02-07 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_user2_remove_user_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User2',
        ),
    ]
