# Generated by Django 5.0.1 on 2024-02-07 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_signin_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signin',
            name='email',
        ),
    ]
