# Generated by Django 5.0.1 on 2024-02-08 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_rename_signin_signup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='password',
            new_name='password2',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='username',
            new_name='username2',
        ),
    ]
