# Generated by Django 5.0.1 on 2024-02-08 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_rename_password_signup_password2_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
