# Generated by Django 5.0.1 on 2024-02-09 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_signup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='email',
            new_name='email2',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='password',
            new_name='password2',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='username',
            new_name='username2',
        ),
    ]
