# Generated by Django 5.0.1 on 2024-02-09 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_rename_email_signup_email2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='email2',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='password2',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='username2',
            new_name='username',
        ),
    ]
