# Generated by Django 5.0.1 on 2024-02-09 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_rename_email2_signup_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='email',
            new_name='email_signup',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='password',
            new_name='password_signup',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='username',
            new_name='username_signup',
        ),
    ]
