# Generated by Django 5.0.1 on 2024-02-10 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_rename_email_signup_email_signup_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='email_signup',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='password_signup',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='username_signup',
            new_name='username',
        ),
    ]
