# Generated by Django 5.0.1 on 2024-02-13 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0019_kandidat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='password',
            new_name='password2',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='username',
            new_name='username2',
        ),
        migrations.AlterField(
            model_name='kandidat',
            name='foto1',
            field=models.ImageField(upload_to='login/static/img'),
        ),
        migrations.AlterField(
            model_name='kandidat',
            name='foto2',
            field=models.ImageField(upload_to='login/static/img'),
        ),
    ]
